/*
 * Gestion des Étudiants, des Inscriptions
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.gestion.etudiants.modeles;

import java.util.Objects;
/**
 * Inscription
 */


public class InscriptionModele {
  private Integer id = null;

  private Integer etudiantId = null;

  private Integer anneeAcademiqueId = null;

  public InscriptionModele id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public InscriptionModele etudiantId(Integer etudiantId) {
    this.etudiantId = etudiantId;
    return this;
  }

   /**
   * Get etudiantId
   * @return etudiantId
  **/
  public Integer getEtudiantId() {
    return etudiantId;
  }

  public void setEtudiantId(Integer etudiantId) {
    this.etudiantId = etudiantId;
  }

  public InscriptionModele anneeAcademiqueId(Integer anneeAcademiqueId) {
    this.anneeAcademiqueId = anneeAcademiqueId;
    return this;
  }

   /**
   * Get anneeAcademiqueId
   * @return anneeAcademiqueId
  **/
  public Integer getAnneeAcademiqueId() {
    return anneeAcademiqueId;
  }

  public void setAnneeAcademiqueId(Integer anneeAcademiqueId) {
    this.anneeAcademiqueId = anneeAcademiqueId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InscriptionModele inscription = (InscriptionModele) o;
    return Objects.equals(this.id, inscription.id) &&
        Objects.equals(this.etudiantId, inscription.etudiantId) &&
        Objects.equals(this.anneeAcademiqueId, inscription.anneeAcademiqueId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, etudiantId, anneeAcademiqueId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Inscription {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    etudiantId: ").append(toIndentedString(etudiantId)).append("\n");
    sb.append("    anneeAcademiqueId: ").append(toIndentedString(anneeAcademiqueId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
