/*
 * Gestion des Étudiants, des Inscriptions
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.gestion.etudiants.modeles;

import java.util.Objects;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
/**
 * InscriptionRequest
 */

@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
public class InscriptionRequest {
  private String nom = null;

  private String prenom = null;

  private Integer etudiantId = null;

  private Integer anneeAcademiqueId = null;


}
